import js from "@eslint/js";
import userscripts from "eslint-plugin-userscripts";

const browserGlobals = {
  window: "readonly",
  document: "readonly",
  console: "readonly",
  MutationObserver: "readonly",
  setTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  navigator: "readonly",
  HTMLElement: "readonly",
  Node: "readonly",
  MouseEvent: "readonly",
  KeyboardEvent: "readonly",
  Event: "readonly",
  NodeList: "readonly",
  URL: "readonly",
  XMLHttpRequest: "readonly",
  fetch: "readonly",
  alert: "readonly",
  prompt: "readonly",
  confirm: "readonly",
  performance: "readonly",
  getComputedStyle: "readonly",
  requestAnimationFrame: "readonly",
  localStorage: "readonly",
  location: "readonly",
  history: "readonly",
  self: "readonly",
  crypto: "readonly",
  atob: "readonly",
  btoa: "readonly",
  TextEncoder: "readonly",
  TextDecoder: "readonly",
  AbortController: "readonly",
  Response: "readonly",
  Headers: "readonly",
  Blob: "readonly",
  FileReader: "readonly",
  Map: "readonly",
  Set: "readonly",
  Promise: "readonly",
  Proxy: "readonly",
  Reflect: "readonly",
  WeakMap: "readonly",
  WeakSet: "readonly",
  Symbol: "readonly",
  structuredClone: "readonly",
};

export default [
  {
    ignores: ["DonkeyCODE/DonkeyCode/baked-config.js", "DonkeyCODE/DonkeyCode/baked-config.template.js", "node_modules/**"],
  },
  js.configs.recommended,
  {
    plugins: { userscripts },
    rules: {
      ...userscripts.configs.recommended.rules,
      "no-unused-vars": "warn",
      "no-undef": "off",
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...browserGlobals,
        GM_xmlhttpRequest: "readonly",
        GM_addStyle: "readonly",
        GM_getValue: "readonly",
        GM_setValue: "readonly",
        GM_registerMenuCommand: "readonly",
        GM_notification: "readonly",
      },
    },
    files: ["*.user.js"],
  },
  {
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "off",
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...browserGlobals,
        chrome: "readonly",
        importScripts: "readonly",
      },
    },
    files: ["DonkeyCODE/DonkeyCode/**/*.js"],
    ignores: ["DonkeyCODE/DonkeyCode/baked-config.js"],
  },
];
